Repository planetarium/NineChronicles.EthBridge, pull requests merged in 2022-10, with the labels that each got.

#204 fix(bridge-www): support sepolia development contract
  bridge-www/package.json
  bridge-www/src/App.tsx
  bridge-www/src/index.tsx
  bridge-www/src/pages/ConnectWallet.tsx
  bridge-www/src/pages/SwapWncg.tsx
  bridge-www/src/wrapped-ncg-token.ts
  bridge-www/yarn.lock
Labels: bug, bridge-www, Medium

#205 feat(bridge): upgrade sqlite3 to 1.5.1 above
  bridge/package.json
  bridge/yarn.lock
Labels: Extra Small

#206 test(bridge): make aws-dependent tests' parameters configurable totally
  bridge/test/aws-dependent/ncg-kms-transfer.aws.spec.ts
Labels: Extra Small

#208 fix(bridge-www): provide injected connector to hook
  bridge-www/src/App.tsx
Labels: bug, bridge-www, Extra Small

#202 Use sphere to sign transactions
  bridge/package.json
  bridge/src/activate-account.ts
  bridge/src/headless-graphql-client.ts
  bridge/src/kms-ncg-signer.ts
  bridge/src/ncg-kms-transfer.ts
  bridge/yarn.lock
Labels: Medium

#209 test(bridge): bump headless version in test environment
  docker-compose.yaml
Labels: bridge, Extra Small
