Repository planetarium/NineChronicles.EthBridge, pull requests merged in 2023-07, with the labels that each got.

#252 used planetarium tx library and modified updatedAddress
  .github/workflows/build-bridge.yaml
  bridge/.dockerignore
  bridge/Dockerfile
  bridge/package.json
  bridge/src/headless-graphql-client.ts
  bridge/src/interfaces/headless-graphql-client.ts
  bridge/src/ncg-kms-transfer.ts
  bridge/test/monitors/nine-chronicles-transferred-event-monitor.spec.ts
  bridge/test/ncg-transfer.spec.ts
  bridge/test/wrapped-ncg-minter.spec.ts
  bridge/yarn.lock
  docker-compose.yaml
Labels: Medium

#254 updated mead gas limit
  bridge/src/ncg-kms-transfer.ts
Labels: Extra Small

#255 Feature/mention subscribers for mint failure
  bridge/package.json
  bridge/src/index.ts
  bridge/src/messages/wrapping-failure-event.ts
  bridge/src/observers/nine-chronicles.ts
  bridge/test/messages/__snapshots__/wrapping-failure-event.spec.ts.snap
  bridge/test/messages/wrapping-failure-event.spec.ts
  bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
  bridge/test/observers/nine-chronicles.spec.ts
Labels: Extra Small

#256 feat: added cold wallet mint case at README
  README.md
Labels: documentation, bridge, Extra Small

#257 fix(bridge-status-bot): use `9c-main-full-state.nine-chronicles.com` as GraphQL endpoint
  bridge-status-bot/app.sh
Labels: bug, bridge-status-bot, Extra Small
